# Generated by Django 4.1.7 on 2023-02-17 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_hermana_fecha_de_nac_alter_prima_fecha_de_nac_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hermana',
            old_name='fecha_de_nac',
            new_name='fechaDeNacimiento',
        ),
        migrations.RenameField(
            model_name='prima',
            old_name='fecha_de_nac',
            new_name='fechaDeNacimiento',
        ),
        migrations.RenameField(
            model_name='tia',
            old_name='fecha_de_nac',
            new_name='fechaDeNacimiento',
        ),
    ]
