# Generated by Django 4.1.7 on 2023-02-17 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_fecha_de_nac_hermana_fechadenacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hermana',
            old_name='fechaDeNacimiento',
            new_name='fechadenacimiento',
        ),
        migrations.RenameField(
            model_name='prima',
            old_name='fechaDeNacimiento',
            new_name='fechadenacimiento',
        ),
        migrations.RenameField(
            model_name='tia',
            old_name='fechaDeNacimiento',
            new_name='fechadenacimiento',
        ),
    ]
